spring:
  datasource:
    url: jdbc:mysql://localhost:3306/main_database
    username: root
    password: lgh2000129
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:mybatis/*.xml
