spring:
  datasource:
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1
    username:
    password:
    driverClassName: org.h2.Driver
    schema: classpath:sql/init-table.sql
    data: classpath:sql/data.sql
mybatis:
  mapper-locations: classpath:mybatis/*.xml