// source: moviedb.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = (function() {
  if (this) { return this; }
  if (typeof window !== 'undefined') { return window; }
  if (typeof global !== 'undefined') { return global; }
  if (typeof self !== 'undefined') { return self; }
  return Function('return this')();
}.call(null));

var google_protobuf_empty_pb = require('google-protobuf/google/protobuf/empty_pb.js');
goog.object.extend(proto, google_protobuf_empty_pb);
goog.exportSymbol('proto.com.guohaohome.moviedb.proto.AllMovieIDListResponse', null, global);
goog.exportSymbol('proto.com.guohaohome.moviedb.proto.InfoByIDRequest', null, global);
goog.exportSymbol('proto.com.guohaohome.moviedb.proto.InfoRequest', null, global);
goog.exportSymbol('proto.com.guohaohome.moviedb.proto.InfoResponse', null, global);
goog.exportSymbol('proto.com.guohaohome.moviedb.proto.LineList', null, global);
goog.exportSymbol('proto.com.guohaohome.moviedb.proto.LineListResponse', null, global);
goog.exportSymbol('proto.com.guohaohome.moviedb.proto.MovieID', null, global);
goog.exportSymbol('proto.com.guohaohome.moviedb.proto.MusicInfo', null, global);
goog.exportSymbol('proto.com.guohaohome.moviedb.proto.MusicListResponse', null, global);
goog.exportSymbol('proto.com.guohaohome.moviedb.proto.ObjectList', null, global);
goog.exportSymbol('proto.com.guohaohome.moviedb.proto.ObjectListRequest', null, global);
goog.exportSymbol('proto.com.guohaohome.moviedb.proto.ObjectListResponse', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.guohaohome.moviedb.proto.MovieID = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.com.guohaohome.moviedb.proto.MovieID, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.com.guohaohome.moviedb.proto.MovieID.displayName = 'proto.com.guohaohome.moviedb.proto.MovieID';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.guohaohome.moviedb.proto.AllMovieIDListResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.com.guohaohome.moviedb.proto.AllMovieIDListResponse.repeatedFields_, null);
};
goog.inherits(proto.com.guohaohome.moviedb.proto.AllMovieIDListResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.com.guohaohome.moviedb.proto.AllMovieIDListResponse.displayName = 'proto.com.guohaohome.moviedb.proto.AllMovieIDListResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.guohaohome.moviedb.proto.InfoResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.com.guohaohome.moviedb.proto.InfoResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.com.guohaohome.moviedb.proto.InfoResponse.displayName = 'proto.com.guohaohome.moviedb.proto.InfoResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.guohaohome.moviedb.proto.InfoByIDRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.com.guohaohome.moviedb.proto.InfoByIDRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.com.guohaohome.moviedb.proto.InfoByIDRequest.displayName = 'proto.com.guohaohome.moviedb.proto.InfoByIDRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.guohaohome.moviedb.proto.InfoRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.com.guohaohome.moviedb.proto.InfoRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.com.guohaohome.moviedb.proto.InfoRequest.displayName = 'proto.com.guohaohome.moviedb.proto.InfoRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.guohaohome.moviedb.proto.ObjectList = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.com.guohaohome.moviedb.proto.ObjectList, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.com.guohaohome.moviedb.proto.ObjectList.displayName = 'proto.com.guohaohome.moviedb.proto.ObjectList';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.guohaohome.moviedb.proto.ObjectListRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.com.guohaohome.moviedb.proto.ObjectListRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.com.guohaohome.moviedb.proto.ObjectListRequest.displayName = 'proto.com.guohaohome.moviedb.proto.ObjectListRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.guohaohome.moviedb.proto.ObjectListResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.com.guohaohome.moviedb.proto.ObjectListResponse.repeatedFields_, null);
};
goog.inherits(proto.com.guohaohome.moviedb.proto.ObjectListResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.com.guohaohome.moviedb.proto.ObjectListResponse.displayName = 'proto.com.guohaohome.moviedb.proto.ObjectListResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.guohaohome.moviedb.proto.LineList = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.com.guohaohome.moviedb.proto.LineList, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.com.guohaohome.moviedb.proto.LineList.displayName = 'proto.com.guohaohome.moviedb.proto.LineList';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.guohaohome.moviedb.proto.LineListResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.com.guohaohome.moviedb.proto.LineListResponse.repeatedFields_, null);
};
goog.inherits(proto.com.guohaohome.moviedb.proto.LineListResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.com.guohaohome.moviedb.proto.LineListResponse.displayName = 'proto.com.guohaohome.moviedb.proto.LineListResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.guohaohome.moviedb.proto.MusicInfo = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.com.guohaohome.moviedb.proto.MusicInfo, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.com.guohaohome.moviedb.proto.MusicInfo.displayName = 'proto.com.guohaohome.moviedb.proto.MusicInfo';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.guohaohome.moviedb.proto.MusicListResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.com.guohaohome.moviedb.proto.MusicListResponse.repeatedFields_, null);
};
goog.inherits(proto.com.guohaohome.moviedb.proto.MusicListResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.com.guohaohome.moviedb.proto.MusicListResponse.displayName = 'proto.com.guohaohome.moviedb.proto.MusicListResponse';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.guohaohome.moviedb.proto.MovieID.prototype.toObject = function(opt_includeInstance) {
  return proto.com.guohaohome.moviedb.proto.MovieID.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.guohaohome.moviedb.proto.MovieID} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.guohaohome.moviedb.proto.MovieID.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.guohaohome.moviedb.proto.MovieID}
 */
proto.com.guohaohome.moviedb.proto.MovieID.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.guohaohome.moviedb.proto.MovieID;
  return proto.com.guohaohome.moviedb.proto.MovieID.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.guohaohome.moviedb.proto.MovieID} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.guohaohome.moviedb.proto.MovieID}
 */
proto.com.guohaohome.moviedb.proto.MovieID.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setId(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.guohaohome.moviedb.proto.MovieID.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.guohaohome.moviedb.proto.MovieID.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.guohaohome.moviedb.proto.MovieID} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.guohaohome.moviedb.proto.MovieID.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string id = 1;
 * @return {string}
 */
proto.com.guohaohome.moviedb.proto.MovieID.prototype.getId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.com.guohaohome.moviedb.proto.MovieID} returns this
 */
proto.com.guohaohome.moviedb.proto.MovieID.prototype.setId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.com.guohaohome.moviedb.proto.AllMovieIDListResponse.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.guohaohome.moviedb.proto.AllMovieIDListResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.com.guohaohome.moviedb.proto.AllMovieIDListResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.guohaohome.moviedb.proto.AllMovieIDListResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.guohaohome.moviedb.proto.AllMovieIDListResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    replyList: jspb.Message.toObjectList(msg.getReplyList(),
    proto.com.guohaohome.moviedb.proto.MovieID.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.guohaohome.moviedb.proto.AllMovieIDListResponse}
 */
proto.com.guohaohome.moviedb.proto.AllMovieIDListResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.guohaohome.moviedb.proto.AllMovieIDListResponse;
  return proto.com.guohaohome.moviedb.proto.AllMovieIDListResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.guohaohome.moviedb.proto.AllMovieIDListResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.guohaohome.moviedb.proto.AllMovieIDListResponse}
 */
proto.com.guohaohome.moviedb.proto.AllMovieIDListResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.com.guohaohome.moviedb.proto.MovieID;
      reader.readMessage(value,proto.com.guohaohome.moviedb.proto.MovieID.deserializeBinaryFromReader);
      msg.addReply(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.guohaohome.moviedb.proto.AllMovieIDListResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.guohaohome.moviedb.proto.AllMovieIDListResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.guohaohome.moviedb.proto.AllMovieIDListResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.guohaohome.moviedb.proto.AllMovieIDListResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getReplyList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.com.guohaohome.moviedb.proto.MovieID.serializeBinaryToWriter
    );
  }
};


/**
 * repeated MovieID reply = 1;
 * @return {!Array<!proto.com.guohaohome.moviedb.proto.MovieID>}
 */
proto.com.guohaohome.moviedb.proto.AllMovieIDListResponse.prototype.getReplyList = function() {
  return /** @type{!Array<!proto.com.guohaohome.moviedb.proto.MovieID>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.com.guohaohome.moviedb.proto.MovieID, 1));
};


/**
 * @param {!Array<!proto.com.guohaohome.moviedb.proto.MovieID>} value
 * @return {!proto.com.guohaohome.moviedb.proto.AllMovieIDListResponse} returns this
*/
proto.com.guohaohome.moviedb.proto.AllMovieIDListResponse.prototype.setReplyList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.com.guohaohome.moviedb.proto.MovieID=} opt_value
 * @param {number=} opt_index
 * @return {!proto.com.guohaohome.moviedb.proto.MovieID}
 */
proto.com.guohaohome.moviedb.proto.AllMovieIDListResponse.prototype.addReply = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.com.guohaohome.moviedb.proto.MovieID, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.com.guohaohome.moviedb.proto.AllMovieIDListResponse} returns this
 */
proto.com.guohaohome.moviedb.proto.AllMovieIDListResponse.prototype.clearReplyList = function() {
  return this.setReplyList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.guohaohome.moviedb.proto.InfoResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.com.guohaohome.moviedb.proto.InfoResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.guohaohome.moviedb.proto.InfoResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.guohaohome.moviedb.proto.InfoResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, ""),
    name: jspb.Message.getFieldWithDefault(msg, 2, ""),
    imdb: jspb.Message.getFloatingPointFieldWithDefault(msg, 3, 0.0),
    tomatoes: jspb.Message.getFieldWithDefault(msg, 4, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.guohaohome.moviedb.proto.InfoResponse}
 */
proto.com.guohaohome.moviedb.proto.InfoResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.guohaohome.moviedb.proto.InfoResponse;
  return proto.com.guohaohome.moviedb.proto.InfoResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.guohaohome.moviedb.proto.InfoResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.guohaohome.moviedb.proto.InfoResponse}
 */
proto.com.guohaohome.moviedb.proto.InfoResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setImdb(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setTomatoes(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.guohaohome.moviedb.proto.InfoResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.guohaohome.moviedb.proto.InfoResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.guohaohome.moviedb.proto.InfoResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.guohaohome.moviedb.proto.InfoResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getImdb();
  if (f !== 0.0) {
    writer.writeDouble(
      3,
      f
    );
  }
  f = message.getTomatoes();
  if (f !== 0) {
    writer.writeInt32(
      4,
      f
    );
  }
};


/**
 * optional string id = 1;
 * @return {string}
 */
proto.com.guohaohome.moviedb.proto.InfoResponse.prototype.getId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.com.guohaohome.moviedb.proto.InfoResponse} returns this
 */
proto.com.guohaohome.moviedb.proto.InfoResponse.prototype.setId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string name = 2;
 * @return {string}
 */
proto.com.guohaohome.moviedb.proto.InfoResponse.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.com.guohaohome.moviedb.proto.InfoResponse} returns this
 */
proto.com.guohaohome.moviedb.proto.InfoResponse.prototype.setName = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional double IMDb = 3;
 * @return {number}
 */
proto.com.guohaohome.moviedb.proto.InfoResponse.prototype.getImdb = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 3, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.com.guohaohome.moviedb.proto.InfoResponse} returns this
 */
proto.com.guohaohome.moviedb.proto.InfoResponse.prototype.setImdb = function(value) {
  return jspb.Message.setProto3FloatField(this, 3, value);
};


/**
 * optional int32 Tomatoes = 4;
 * @return {number}
 */
proto.com.guohaohome.moviedb.proto.InfoResponse.prototype.getTomatoes = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.com.guohaohome.moviedb.proto.InfoResponse} returns this
 */
proto.com.guohaohome.moviedb.proto.InfoResponse.prototype.setTomatoes = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.guohaohome.moviedb.proto.InfoByIDRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.com.guohaohome.moviedb.proto.InfoByIDRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.guohaohome.moviedb.proto.InfoByIDRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.guohaohome.moviedb.proto.InfoByIDRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.guohaohome.moviedb.proto.InfoByIDRequest}
 */
proto.com.guohaohome.moviedb.proto.InfoByIDRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.guohaohome.moviedb.proto.InfoByIDRequest;
  return proto.com.guohaohome.moviedb.proto.InfoByIDRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.guohaohome.moviedb.proto.InfoByIDRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.guohaohome.moviedb.proto.InfoByIDRequest}
 */
proto.com.guohaohome.moviedb.proto.InfoByIDRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setId(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.guohaohome.moviedb.proto.InfoByIDRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.guohaohome.moviedb.proto.InfoByIDRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.guohaohome.moviedb.proto.InfoByIDRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.guohaohome.moviedb.proto.InfoByIDRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string id = 1;
 * @return {string}
 */
proto.com.guohaohome.moviedb.proto.InfoByIDRequest.prototype.getId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.com.guohaohome.moviedb.proto.InfoByIDRequest} returns this
 */
proto.com.guohaohome.moviedb.proto.InfoByIDRequest.prototype.setId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.guohaohome.moviedb.proto.InfoRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.com.guohaohome.moviedb.proto.InfoRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.guohaohome.moviedb.proto.InfoRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.guohaohome.moviedb.proto.InfoRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, ""),
    name: jspb.Message.getFieldWithDefault(msg, 2, ""),
    imdb: jspb.Message.getFloatingPointFieldWithDefault(msg, 3, 0.0),
    tomatoes: jspb.Message.getFieldWithDefault(msg, 4, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.guohaohome.moviedb.proto.InfoRequest}
 */
proto.com.guohaohome.moviedb.proto.InfoRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.guohaohome.moviedb.proto.InfoRequest;
  return proto.com.guohaohome.moviedb.proto.InfoRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.guohaohome.moviedb.proto.InfoRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.guohaohome.moviedb.proto.InfoRequest}
 */
proto.com.guohaohome.moviedb.proto.InfoRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setImdb(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setTomatoes(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.guohaohome.moviedb.proto.InfoRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.guohaohome.moviedb.proto.InfoRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.guohaohome.moviedb.proto.InfoRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.guohaohome.moviedb.proto.InfoRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getImdb();
  if (f !== 0.0) {
    writer.writeDouble(
      3,
      f
    );
  }
  f = message.getTomatoes();
  if (f !== 0) {
    writer.writeInt32(
      4,
      f
    );
  }
};


/**
 * optional string id = 1;
 * @return {string}
 */
proto.com.guohaohome.moviedb.proto.InfoRequest.prototype.getId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.com.guohaohome.moviedb.proto.InfoRequest} returns this
 */
proto.com.guohaohome.moviedb.proto.InfoRequest.prototype.setId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string name = 2;
 * @return {string}
 */
proto.com.guohaohome.moviedb.proto.InfoRequest.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.com.guohaohome.moviedb.proto.InfoRequest} returns this
 */
proto.com.guohaohome.moviedb.proto.InfoRequest.prototype.setName = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional double IMDb = 3;
 * @return {number}
 */
proto.com.guohaohome.moviedb.proto.InfoRequest.prototype.getImdb = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 3, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.com.guohaohome.moviedb.proto.InfoRequest} returns this
 */
proto.com.guohaohome.moviedb.proto.InfoRequest.prototype.setImdb = function(value) {
  return jspb.Message.setProto3FloatField(this, 3, value);
};


/**
 * optional int32 Tomatoes = 4;
 * @return {number}
 */
proto.com.guohaohome.moviedb.proto.InfoRequest.prototype.getTomatoes = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.com.guohaohome.moviedb.proto.InfoRequest} returns this
 */
proto.com.guohaohome.moviedb.proto.InfoRequest.prototype.setTomatoes = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.guohaohome.moviedb.proto.ObjectList.prototype.toObject = function(opt_includeInstance) {
  return proto.com.guohaohome.moviedb.proto.ObjectList.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.guohaohome.moviedb.proto.ObjectList} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.guohaohome.moviedb.proto.ObjectList.toObject = function(includeInstance, msg) {
  var f, obj = {
    objectname: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.guohaohome.moviedb.proto.ObjectList}
 */
proto.com.guohaohome.moviedb.proto.ObjectList.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.guohaohome.moviedb.proto.ObjectList;
  return proto.com.guohaohome.moviedb.proto.ObjectList.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.guohaohome.moviedb.proto.ObjectList} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.guohaohome.moviedb.proto.ObjectList}
 */
proto.com.guohaohome.moviedb.proto.ObjectList.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setObjectname(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.guohaohome.moviedb.proto.ObjectList.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.guohaohome.moviedb.proto.ObjectList.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.guohaohome.moviedb.proto.ObjectList} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.guohaohome.moviedb.proto.ObjectList.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getObjectname();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string ObjectName = 1;
 * @return {string}
 */
proto.com.guohaohome.moviedb.proto.ObjectList.prototype.getObjectname = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.com.guohaohome.moviedb.proto.ObjectList} returns this
 */
proto.com.guohaohome.moviedb.proto.ObjectList.prototype.setObjectname = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.guohaohome.moviedb.proto.ObjectListRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.com.guohaohome.moviedb.proto.ObjectListRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.guohaohome.moviedb.proto.ObjectListRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.guohaohome.moviedb.proto.ObjectListRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    bucketname: jspb.Message.getFieldWithDefault(msg, 1, ""),
    keyprefix: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.guohaohome.moviedb.proto.ObjectListRequest}
 */
proto.com.guohaohome.moviedb.proto.ObjectListRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.guohaohome.moviedb.proto.ObjectListRequest;
  return proto.com.guohaohome.moviedb.proto.ObjectListRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.guohaohome.moviedb.proto.ObjectListRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.guohaohome.moviedb.proto.ObjectListRequest}
 */
proto.com.guohaohome.moviedb.proto.ObjectListRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setBucketname(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setKeyprefix(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.guohaohome.moviedb.proto.ObjectListRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.guohaohome.moviedb.proto.ObjectListRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.guohaohome.moviedb.proto.ObjectListRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.guohaohome.moviedb.proto.ObjectListRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getBucketname();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getKeyprefix();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional string bucketName = 1;
 * @return {string}
 */
proto.com.guohaohome.moviedb.proto.ObjectListRequest.prototype.getBucketname = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.com.guohaohome.moviedb.proto.ObjectListRequest} returns this
 */
proto.com.guohaohome.moviedb.proto.ObjectListRequest.prototype.setBucketname = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string keyPrefix = 2;
 * @return {string}
 */
proto.com.guohaohome.moviedb.proto.ObjectListRequest.prototype.getKeyprefix = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.com.guohaohome.moviedb.proto.ObjectListRequest} returns this
 */
proto.com.guohaohome.moviedb.proto.ObjectListRequest.prototype.setKeyprefix = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.com.guohaohome.moviedb.proto.ObjectListResponse.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.guohaohome.moviedb.proto.ObjectListResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.com.guohaohome.moviedb.proto.ObjectListResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.guohaohome.moviedb.proto.ObjectListResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.guohaohome.moviedb.proto.ObjectListResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    replyList: jspb.Message.toObjectList(msg.getReplyList(),
    proto.com.guohaohome.moviedb.proto.ObjectList.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.guohaohome.moviedb.proto.ObjectListResponse}
 */
proto.com.guohaohome.moviedb.proto.ObjectListResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.guohaohome.moviedb.proto.ObjectListResponse;
  return proto.com.guohaohome.moviedb.proto.ObjectListResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.guohaohome.moviedb.proto.ObjectListResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.guohaohome.moviedb.proto.ObjectListResponse}
 */
proto.com.guohaohome.moviedb.proto.ObjectListResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.com.guohaohome.moviedb.proto.ObjectList;
      reader.readMessage(value,proto.com.guohaohome.moviedb.proto.ObjectList.deserializeBinaryFromReader);
      msg.addReply(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.guohaohome.moviedb.proto.ObjectListResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.guohaohome.moviedb.proto.ObjectListResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.guohaohome.moviedb.proto.ObjectListResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.guohaohome.moviedb.proto.ObjectListResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getReplyList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.com.guohaohome.moviedb.proto.ObjectList.serializeBinaryToWriter
    );
  }
};


/**
 * repeated ObjectList reply = 1;
 * @return {!Array<!proto.com.guohaohome.moviedb.proto.ObjectList>}
 */
proto.com.guohaohome.moviedb.proto.ObjectListResponse.prototype.getReplyList = function() {
  return /** @type{!Array<!proto.com.guohaohome.moviedb.proto.ObjectList>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.com.guohaohome.moviedb.proto.ObjectList, 1));
};


/**
 * @param {!Array<!proto.com.guohaohome.moviedb.proto.ObjectList>} value
 * @return {!proto.com.guohaohome.moviedb.proto.ObjectListResponse} returns this
*/
proto.com.guohaohome.moviedb.proto.ObjectListResponse.prototype.setReplyList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.com.guohaohome.moviedb.proto.ObjectList=} opt_value
 * @param {number=} opt_index
 * @return {!proto.com.guohaohome.moviedb.proto.ObjectList}
 */
proto.com.guohaohome.moviedb.proto.ObjectListResponse.prototype.addReply = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.com.guohaohome.moviedb.proto.ObjectList, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.com.guohaohome.moviedb.proto.ObjectListResponse} returns this
 */
proto.com.guohaohome.moviedb.proto.ObjectListResponse.prototype.clearReplyList = function() {
  return this.setReplyList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.guohaohome.moviedb.proto.LineList.prototype.toObject = function(opt_includeInstance) {
  return proto.com.guohaohome.moviedb.proto.LineList.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.guohaohome.moviedb.proto.LineList} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.guohaohome.moviedb.proto.LineList.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, ""),
    sentence: jspb.Message.getFieldWithDefault(msg, 2, ""),
    author: jspb.Message.getFieldWithDefault(msg, 3, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.guohaohome.moviedb.proto.LineList}
 */
proto.com.guohaohome.moviedb.proto.LineList.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.guohaohome.moviedb.proto.LineList;
  return proto.com.guohaohome.moviedb.proto.LineList.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.guohaohome.moviedb.proto.LineList} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.guohaohome.moviedb.proto.LineList}
 */
proto.com.guohaohome.moviedb.proto.LineList.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setSentence(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setAuthor(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.guohaohome.moviedb.proto.LineList.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.guohaohome.moviedb.proto.LineList.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.guohaohome.moviedb.proto.LineList} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.guohaohome.moviedb.proto.LineList.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getSentence();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getAuthor();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
};


/**
 * optional string id = 1;
 * @return {string}
 */
proto.com.guohaohome.moviedb.proto.LineList.prototype.getId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.com.guohaohome.moviedb.proto.LineList} returns this
 */
proto.com.guohaohome.moviedb.proto.LineList.prototype.setId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string sentence = 2;
 * @return {string}
 */
proto.com.guohaohome.moviedb.proto.LineList.prototype.getSentence = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.com.guohaohome.moviedb.proto.LineList} returns this
 */
proto.com.guohaohome.moviedb.proto.LineList.prototype.setSentence = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string author = 3;
 * @return {string}
 */
proto.com.guohaohome.moviedb.proto.LineList.prototype.getAuthor = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.com.guohaohome.moviedb.proto.LineList} returns this
 */
proto.com.guohaohome.moviedb.proto.LineList.prototype.setAuthor = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.com.guohaohome.moviedb.proto.LineListResponse.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.guohaohome.moviedb.proto.LineListResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.com.guohaohome.moviedb.proto.LineListResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.guohaohome.moviedb.proto.LineListResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.guohaohome.moviedb.proto.LineListResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    replyList: jspb.Message.toObjectList(msg.getReplyList(),
    proto.com.guohaohome.moviedb.proto.LineList.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.guohaohome.moviedb.proto.LineListResponse}
 */
proto.com.guohaohome.moviedb.proto.LineListResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.guohaohome.moviedb.proto.LineListResponse;
  return proto.com.guohaohome.moviedb.proto.LineListResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.guohaohome.moviedb.proto.LineListResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.guohaohome.moviedb.proto.LineListResponse}
 */
proto.com.guohaohome.moviedb.proto.LineListResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.com.guohaohome.moviedb.proto.LineList;
      reader.readMessage(value,proto.com.guohaohome.moviedb.proto.LineList.deserializeBinaryFromReader);
      msg.addReply(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.guohaohome.moviedb.proto.LineListResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.guohaohome.moviedb.proto.LineListResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.guohaohome.moviedb.proto.LineListResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.guohaohome.moviedb.proto.LineListResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getReplyList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.com.guohaohome.moviedb.proto.LineList.serializeBinaryToWriter
    );
  }
};


/**
 * repeated LineList reply = 1;
 * @return {!Array<!proto.com.guohaohome.moviedb.proto.LineList>}
 */
proto.com.guohaohome.moviedb.proto.LineListResponse.prototype.getReplyList = function() {
  return /** @type{!Array<!proto.com.guohaohome.moviedb.proto.LineList>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.com.guohaohome.moviedb.proto.LineList, 1));
};


/**
 * @param {!Array<!proto.com.guohaohome.moviedb.proto.LineList>} value
 * @return {!proto.com.guohaohome.moviedb.proto.LineListResponse} returns this
*/
proto.com.guohaohome.moviedb.proto.LineListResponse.prototype.setReplyList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.com.guohaohome.moviedb.proto.LineList=} opt_value
 * @param {number=} opt_index
 * @return {!proto.com.guohaohome.moviedb.proto.LineList}
 */
proto.com.guohaohome.moviedb.proto.LineListResponse.prototype.addReply = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.com.guohaohome.moviedb.proto.LineList, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.com.guohaohome.moviedb.proto.LineListResponse} returns this
 */
proto.com.guohaohome.moviedb.proto.LineListResponse.prototype.clearReplyList = function() {
  return this.setReplyList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.guohaohome.moviedb.proto.MusicInfo.prototype.toObject = function(opt_includeInstance) {
  return proto.com.guohaohome.moviedb.proto.MusicInfo.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.guohaohome.moviedb.proto.MusicInfo} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.guohaohome.moviedb.proto.MusicInfo.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, ""),
    address: jspb.Message.getFieldWithDefault(msg, 2, ""),
    musicname: jspb.Message.getFieldWithDefault(msg, 3, ""),
    artist: jspb.Message.getFieldWithDefault(msg, 4, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.guohaohome.moviedb.proto.MusicInfo}
 */
proto.com.guohaohome.moviedb.proto.MusicInfo.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.guohaohome.moviedb.proto.MusicInfo;
  return proto.com.guohaohome.moviedb.proto.MusicInfo.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.guohaohome.moviedb.proto.MusicInfo} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.guohaohome.moviedb.proto.MusicInfo}
 */
proto.com.guohaohome.moviedb.proto.MusicInfo.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setAddress(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setMusicname(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setArtist(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.guohaohome.moviedb.proto.MusicInfo.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.guohaohome.moviedb.proto.MusicInfo.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.guohaohome.moviedb.proto.MusicInfo} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.guohaohome.moviedb.proto.MusicInfo.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getAddress();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getMusicname();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getArtist();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
};


/**
 * optional string id = 1;
 * @return {string}
 */
proto.com.guohaohome.moviedb.proto.MusicInfo.prototype.getId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.com.guohaohome.moviedb.proto.MusicInfo} returns this
 */
proto.com.guohaohome.moviedb.proto.MusicInfo.prototype.setId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string address = 2;
 * @return {string}
 */
proto.com.guohaohome.moviedb.proto.MusicInfo.prototype.getAddress = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.com.guohaohome.moviedb.proto.MusicInfo} returns this
 */
proto.com.guohaohome.moviedb.proto.MusicInfo.prototype.setAddress = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string musicName = 3;
 * @return {string}
 */
proto.com.guohaohome.moviedb.proto.MusicInfo.prototype.getMusicname = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.com.guohaohome.moviedb.proto.MusicInfo} returns this
 */
proto.com.guohaohome.moviedb.proto.MusicInfo.prototype.setMusicname = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string artist = 4;
 * @return {string}
 */
proto.com.guohaohome.moviedb.proto.MusicInfo.prototype.getArtist = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.com.guohaohome.moviedb.proto.MusicInfo} returns this
 */
proto.com.guohaohome.moviedb.proto.MusicInfo.prototype.setArtist = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.com.guohaohome.moviedb.proto.MusicListResponse.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.guohaohome.moviedb.proto.MusicListResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.com.guohaohome.moviedb.proto.MusicListResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.guohaohome.moviedb.proto.MusicListResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.guohaohome.moviedb.proto.MusicListResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    replyList: jspb.Message.toObjectList(msg.getReplyList(),
    proto.com.guohaohome.moviedb.proto.MusicInfo.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.guohaohome.moviedb.proto.MusicListResponse}
 */
proto.com.guohaohome.moviedb.proto.MusicListResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.guohaohome.moviedb.proto.MusicListResponse;
  return proto.com.guohaohome.moviedb.proto.MusicListResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.guohaohome.moviedb.proto.MusicListResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.guohaohome.moviedb.proto.MusicListResponse}
 */
proto.com.guohaohome.moviedb.proto.MusicListResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.com.guohaohome.moviedb.proto.MusicInfo;
      reader.readMessage(value,proto.com.guohaohome.moviedb.proto.MusicInfo.deserializeBinaryFromReader);
      msg.addReply(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.guohaohome.moviedb.proto.MusicListResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.guohaohome.moviedb.proto.MusicListResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.guohaohome.moviedb.proto.MusicListResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.guohaohome.moviedb.proto.MusicListResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getReplyList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.com.guohaohome.moviedb.proto.MusicInfo.serializeBinaryToWriter
    );
  }
};


/**
 * repeated MusicInfo reply = 1;
 * @return {!Array<!proto.com.guohaohome.moviedb.proto.MusicInfo>}
 */
proto.com.guohaohome.moviedb.proto.MusicListResponse.prototype.getReplyList = function() {
  return /** @type{!Array<!proto.com.guohaohome.moviedb.proto.MusicInfo>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.com.guohaohome.moviedb.proto.MusicInfo, 1));
};


/**
 * @param {!Array<!proto.com.guohaohome.moviedb.proto.MusicInfo>} value
 * @return {!proto.com.guohaohome.moviedb.proto.MusicListResponse} returns this
*/
proto.com.guohaohome.moviedb.proto.MusicListResponse.prototype.setReplyList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.com.guohaohome.moviedb.proto.MusicInfo=} opt_value
 * @param {number=} opt_index
 * @return {!proto.com.guohaohome.moviedb.proto.MusicInfo}
 */
proto.com.guohaohome.moviedb.proto.MusicListResponse.prototype.addReply = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.com.guohaohome.moviedb.proto.MusicInfo, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.com.guohaohome.moviedb.proto.MusicListResponse} returns this
 */
proto.com.guohaohome.moviedb.proto.MusicListResponse.prototype.clearReplyList = function() {
  return this.setReplyList([]);
};


goog.object.extend(exports, proto.com.guohaohome.moviedb.proto);
